##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:
  # Add 'label1' to any changes within 'example' folder or any subfolders
  CoreChanges:
    - src/**/*

  # Add 'label2' to any file changes within 'example2' folder
  Workflow:
    - .github/*

  # Complex: Add 'area/core' label to any change within the 'core' package
  Assets:
    - public/* 

  # Add 'test' label to any change to *.spec.js files within the source dir
  documentation:
    - src/**/*.md

##### Greetings ########################################################################################################
# Comment to be posted to welcome users when they open their first PR
firstPRWelcomeComment: >
  Thanks for opening this pull request 🎉🎉! Please check out our contributing guidelines and provide us atleast 24 hours to review this PR

# Comment to be posted to congratulate user on their first merged PR
firstPRMergeComment: >
  Awesome work 🎊🎊, congrats on your first merged pull request!

# Comment to be posted to on first time issues
firstIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template! Also please provide us some ti!e to get back to you on this.

###### PR/Branch Up-To-Date Checker ####################################################################################
# Check if the branch is up to date with master when certain files are modified
checkUpToDate:
  # The default branch is "master", change the branch if you want to check against a different target branch  
  targetBranch: master
  files:
  # File paths that you want to check for
  # In this example, it checks if the branch is up to date when alembic migrations are modified in the PR.
  # It helps avoid multiple heads in alembic migrations in a collaborative development project.
    - airflow/migrations/*
    - airflow/migrations/**/*
    - airflow/alembic.ini
